;(function () {
	"use strict"
	window.App = window.App || {}

	// Storage utilities with namespacing and safety
	window.App.Storage = {
		load: function (key, fallback) {
			try {
				const raw = localStorage.getItem("naija:" + key)
				if (!raw) return fallback
				return JSON.parse(raw)
			} catch (e) {
				console.error("Storage load failed", key, e)
				return fallback
			}
		},
		save: function (key, value) {
			try {
				localStorage.setItem("naija:" + key, JSON.stringify(value))
			} catch (e) {
				console.error("Storage save failed", key, e)
			}
		},
	}

	// Utilities
	window.App.Utils = {
		slug: function (str) {
			return String(str || "")
				.toLowerCase()
				.replace(/[^a-z0-9]+/g, "-")
				.replace(/(^-|-$)+/g, "")
		},
		uid: function () {
			return "id_" + Math.random().toString(36).slice(2, 9)
		},
		minutes: function (n) {
			return n + " min"
		},
	}

	// Seed recipes (Nigerian dishes)
	const seeds = [
		{
			id: "jollof-rice",
			name: "Jollof Rice",
			description:
				"Smoky, party-style rice simmered in rich tomato and pepper base.",
			servings: 6,
			time: 60,
			color: "#FFF2E7",
			image: "assets/images/jollof-88b17c72.webp",
			ingredients: [
				{ item: "Parboiled rice", qty: 4, unit: "cups" },
				{ item: "Tomatoes", qty: 6, unit: "pcs" },
				{ item: "Red bell peppers", qty: 3, unit: "pcs" },
				{ item: "Onions", qty: 2, unit: "pcs" },
				{ item: "Tomato paste", qty: 2, unit: "tbsp" },
				{ item: "Chicken stock", qty: 3, unit: "cups" },
				{ item: "Vegetable oil", qty: 0.5, unit: "cup" },
				{ item: "Bay leaf", qty: 2, unit: "pcs" },
				{ item: "Salt", qty: 1, unit: "to taste" },
			],
			steps: [
				"Blend tomatoes, peppers, and one onion into a smooth puree.",
				"Fry tomato paste in oil until it darkens slightly and loses its raw taste.",
				"Add blended mix and cook down until thick and aromatic.",
				"Add stock, bay leaves, and seasonings. Stir in parboiled rice.",
				"Reduce heat, cover, and steam until rice is cooked and smoky.",
				"Fluff with a wooden spoon and serve hot.",
			],
		},
		{
			id: "egusi-soup",
			name: "Egusi Soup",
			description: "Melon seed soup with leafy greens and assorted proteins.",
			servings: 5,
			time: 55,
			color: "#E6F6EF",
			image: "assets/images/egusi.png",
			ingredients: [
				{ item: "Ground egusi", qty: 2, unit: "cups" },
				{ item: "Palm oil", qty: 0.5, unit: "cup" },
				{ item: "Stock fish", qty: 1, unit: "cup" },
				{ item: "Beef or goat meat", qty: 500, unit: "g" },
				{ item: "Spinach or ugu", qty: 3, unit: "cups" },
				{ item: "Onion", qty: 1, unit: "pc" },
				{ item: "Crayfish", qty: 2, unit: "tbsp" },
				{ item: "Pepper mix", qty: 1, unit: "cup" },
				{ item: "Seasoning and salt", qty: 1, unit: "to taste" },
			],
			steps: [
				"Heat palm oil, add onions and crayfish; sauté until fragrant.",
				"Stir in pepper mix, cook for a few minutes.",
				"Add ground egusi, stir and allow to fry slightly.",
				"Add meats, stock fish, and some stock; simmer.",
				"Add leafy greens and adjust seasoning.",
				"Serve with pounded yam, eba, or fufu.",
			],
		},
		{
			id: "pounded-yam",
			name: "Pounded Yam",
			image: "assets/images/pounded-yam.png",
			description: "Smooth, stretchy Nigerian staple made from boiled yam",
			time: 30,
			servings: 4,
			ingredients: [
				{ item: "2 lbs yam tuber", qty: 1, unit: "pcs" },
				{ item: "Seasoning and salt", qty: 1, unit: "to taste" },
			],
			steps: [
				"Peel and cut yam into chunks",
				"Boil yam until very soft",
				"Drain and pound until smooth",
				"Serve immediately while hot",
			],
		},
		{
			id: "suya",
			name: "Suya",
			description:
				"Spicy skewered beef with kuli-kuli spice rub grilled to perfection.",
			servings: 4,
			time: 30,
			color: "#FFF9F3",
			image: "assets/images/suya.png",
			ingredients: [
				{ item: "Beef (thin strips)", qty: 600, unit: "g" },
				{ item: "Suya spice (yaji)", qty: 4, unit: "tbsp" },
				{ item: "Groundnut oil", qty: 2, unit: "tbsp" },
				{ item: "Salt", qty: 1, unit: "to taste" },
				{ item: "Onions (rings)", qty: 1, unit: "pc" },
				{ item: "Cabbage", qty: 1, unit: "cup" },
			],
			steps: [
				"Toss beef in oil and suya spice; thread onto skewers.",
				"Grill on medium-high heat until cooked, basting with oil if needed.",
				"Serve with fresh onions, tomatoes, and cabbage.",
			],
		},
		{
			id: "pepper-soup",
			name: "Pepper Soup",
			image: "assets/images/pepper-soup.png",
			description: "Spicy Nigerian soup perfect for cold days",
			time: 40,
			servings: 6,
			difficulty: "Medium",
			ingredients: [
				{ item: "catfish", qty: 2, unit: "lbs" },
				{ item: "pepper soup spice", qty: 1, unit: "tbsp" },
				{ item: "Onions (rings)", qty: 1, unit: "pc" },
				{ item: "scotch bonnet peppers", qty: 3, unit: "pcs" },
				{ item: "crayfish", qty: 2, unit: "tbsp" },
				{ item: "scent leave", qty: 1, unit: "pcs" },
			],
			steps: [
				"Season fish with salt and pepper soup spice",
				"Boil water with onions and peppers",
				"Add seasoned fish and cook for 15 minutes",
				"Add crayfish and remaining spices",
				"Simmer for 20 minutes",
				"Garnish with scent leaves before serving",
			],
		},
		{
			id: "akara",
			name: "Akara",
			image: "assets/images/akara.png",
			description: "Deep-fried bean cakes, perfect for breakfast",
			time: 20,
			servings: 4,
			difficulty: "Medium",
			ingredients: [
				{ item: "black-eyed beans", qty: 2, unit: "cups" },
				{ item: "scotch bonnet peppers", qty: 3, unit: "pcs" },
				{ item: "Salt", qty: 1, unit: "to taste" },
				{ item: "Oil for deep frying", qty: 1, unit: "enough" },
				{ item: "Onions (rings)", qty: 1, unit: "pc" },
			],
			steps: [
				"Soak beans overnight and remove skins",
				"Blend beans with onion and pepper",
				"Season batter with salt",
				"Heat oil for deep frying",
				"Drop spoonfuls of batter into hot oil",
				"Fry until golden brown and crispy",
			],
		},
		{
			id: "afang-soup",
			name: "Afang Soup",
			image: "assets/images/afang-ed3423a9.webp",
			description: "Rich vegetable soup made with waterleaf and afang leaves",
			time: 50,
			servings: 6,
			difficulty: "Hard",
			ingredients: [
				{ item: "waterleaf or spinach", qty: 3, unit: "cups" },
				{ item: "afang leaves (okazi leaves)", qty: 2, unit: "cups" },
				{ item: "assorted meat", qty: 1, unit: "lb" },
				{ item: "periwinkle (optional)", qty: 1, unit: "cup" },
				{ item: "palm oil", qty: 0.25, unit: "cup" },
				{ item: "onion", qty: 1, unit: "pc" },
				{ item: "ground crayfish", qty: 2, unit: "tbsp" },
				{ item: "stock cubes", qty: 2, unit: "pcs" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
				{ item: "scotch bonnet peppers", qty: 2, unit: "pcs" },
			],
			steps: [
				"Cook meat until tender",
				"Add palm oil in a pot and sauté onions",
				"Add meat, crayfish, and stock cubes",
				"Add waterleaf and cook for 10 minutes",
				"Add afang leaves and simmer for another 10 minutes",
				"Add salt and peppers to taste",
			],
		},
		{
			id: "moi-moi",
			name: "Moi Moi",
			image: "assets/images/moi-moi.png",
			description: "Steamed bean pudding made with black-eyed peas and spices",
			time: 1,
			servings: 8,
			difficulty: "Medium",
			ingredients: [
				{ item: "peeled black-eyed peas", qty: 2, unit: "cups" },
				{ item: "onion", qty: 1, unit: "pc" },
				{ item: "red bell pepper", qty: 1, unit: "pc" },
				{ item: "scotch bonnet pepper", qty: 1, unit: "pc" },
				{ item: "vegetable oil", qty: 0.25, unit: "cup" },
				{ item: "seasoning powder", qty: 2, unit: "tsp" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
			],
			steps: [
				"Soak beans and peel skins",
				"Blend beans with peppers and onions adding water as needed",
				"Add oil, seasoning, and salt, mix well",
				"Pour mixture into containers or leaves",
				"Steam for 45 minutes to 1 hour",
			],
		},
		{
			id: "efo-riro",
			name: "Efo Riro",
			image: "assets/images/efo-riro.png",
			description: "Delicious Nigerian spinach stew with meat and fish",
			time: 45,
			servings: 6,
			difficulty: "Medium",
			ingredients: [
				{ item: "chopped spinach", qty: 4, unit: "cups" },
				{ item: "assorted meat", qty: 1, unit: "lb" },
				{ item: "stockfish", qty: 0.5, unit: "lb" },
				{ item: "palm oil", qty: 0.25, unit: "cup" },
				{ item: "large tomatoes", qty: 2, unit: "pcs" },
				{ item: "onion", qty: 1, unit: "pc" },
				{ item: "scotch bonnet pepper", qty: 1, unit: "pc" },
				{ item: "ground crayfish", qty: 2, unit: "tbsp" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
			],
			steps: [
				"Cook meat and stockfish until tender",
				"Heat palm oil and fry onions",
				"Add blended tomatoes and cook until oil separates",
				"Add meat, fish, crayfish, and peppers",
				"Add spinach and simmer for 10 minutes",
				"Add salt to taste",
			],
		},
		{
			id: "bitterleaf-soup",
			name: "Bitterleaf Soup (Ofe Onugbu)",
			image: "assets/images/bitterleaf-soup.png",
			description:
				"Traditional Igbo soup made with bitterleaf and assorted meats",
			time: 60,
			servings: 6,
			difficulty: "Hard",
			ingredients: [
				{ item: "washed bitterleaf", qty: 4, unit: "cups" },
				{ item: "assorted meat", qty: 1, unit: "lb" },
				{ item: "stockfish", qty: 0.5, unit: "lb" },
				{ item: "palm oil", qty: 0.25, unit: "cup" },
				{ item: "onion", qty: 1, unit: "pc" },
				{ item: "ground crayfish", qty: 2, unit: "tbsp" },
				{ item: "stock cubes", qty: 2, unit: "pcs" },
				{ item: "large tomatoes", qty: 2, unit: "pcs" },
				{ item: "scotch bonnet pepper", qty: 2, unit: "pc" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
			],
			steps: [
				"Cook meat and stockfish until tender",
				"Add palm oil and fry onions",
				"Add meat, crayfish, stock cubes, and peppers",
				"Add washed bitterleaf and simmer for 20 minutes",
				"Add salt to taste",
			],
		},
		{
			id: "fried-plantain",
			name: "Fried Plantain (Dodo)",
			image: "assets/images/fried-plantain.png",
			description: "Sweet fried ripe plantains, a popular side dish",
			time: 15,
			servings: 4,
			difficulty: "Easy",
			ingredients: [
				{ item: "ripe plantains", qty: 3, unit: "pcs" },
				{ item: "vegetable oil for frying", qty: 1, unit: "enough" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
			],
			steps: [
				"Peel and slice plantains diagonally",
				"Heat oil in a frying pan",
				"Fry plantain slices until golden brown",
				"Drain on paper towels and sprinkle salt",
			],
		},
		{
			id: "nkwobi",
			name: "Nkwobi",
			image: "assets/images/nkwobi.png",
			description: "Spicy cow foot dish popular in Eastern Nigeria",
			time: 120,
			servings: 6,
			difficulty: "Hard",
			ingredients: [
				{ item: "cow foot", qty: 2, unit: "lbs" },
				{ item: "palm oil", qty: 0.25, unit: "cup" },
				{ item: "potash solution", qty: 2, unit: "tbsp" },
				{ item: "ground crayfish", qty: 2, unit: "tbsp" },
				{ item: "ugba (oil bean seeds)", qty: 2, unit: "tbsp" },
				{ item: "scotch bonnet peppers", qty: 2, unit: "pcs" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
				{
					item: "Onions and utazi leaves for garnish",
					qty: 1,
					unit: "as needed",
				},
			],
			steps: [
				"Boil cow foot until tender",
				"Mix palm oil and potash solution until thickened",
				"Add ground crayfish, ugba, and peppers",
				"Stir in cow foot pieces",
				"Garnish with onions",
			],
		},
		{
			id: "okro-soup",
			name: "Okro Soup",
			image: "assets/images/okro-soup.jpg",
			description:
				"Slimy and savory Nigerian soup made with okra and assorted proteins",
			time: 35,
			servings: 5,
			difficulty: "Medium",
			ingredients: [
				{ item: "chopped okra", qty: 3, unit: "cups" },
				{ item: "stockfish", qty: 0.5, unit: "lb" },
				{ item: "assorted meat", qty: 1, unit: "lb" },
				{ item: "palm oil", qty: 0.25, unit: "cup" },
				{ item: "ground crayfish", qty: 2, unit: "tbsp" },
				{ item: "stock cubes", qty: 2, unit: "pcs" },
				{ item: "scotch bonnet peppers", qty: 2, unit: "pcs" },
				{ item: "small onion", qty: 1, unit: "pc" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
			],
			steps: [
				"Cook meat and stockfish until tender",
				"Heat palm oil, sauté onions and pepper",
				"Add crayfish, meat, and stock",
				"Add chopped okra and cook for 10-15 mins",
				"Season with salt and stock cubes",
			],
		},
		{
			id: "beans-and-dodo",
			name: "Beans and Dodo",
			image: "assets/images/beans-and-dodo.jpg",
			description: "Nigerian-style stewed beans served with fried plantains",
			time: 60,
			servings: 4,
			difficulty: "Easy",
			ingredients: [
				{ item: "honey bean", qty: 2, unit: "cups" },
				{ item: "onion", qty: 1, unit: "pc" },
				{ item: "palm oil", qty: 2, unit: "tbsp" },
				{ item: "salt", qty: 1, unit: "to taste" },
				{ item: "ripe plantains", qty: 3, unit: "pcs" },
				{ item: "vegetable oil for frying", qty: 1, unit: "enough" },
			],
			steps: [
				"Boil beans with onions until soft",
				"Add palm oil and season with salt",
				"Slice plantains and fry until golden",
				"Serve beans with fried plantains",
			],
		},
		{
			id: "oha-soup",
			name: "Oha Soup",
			image: "assets/images/oha-soup.jpg",
			description:
				"A native Igbo soup made with Oha leaves and thickened with cocoyam",
			time: 60,
			servings: 6,
			difficulty: "Hard",
			ingredients: [
				{ item: "shredded Oha leaves", qty: 2, unit: "cups" },
				{ item: "assorted meat", qty: 1, unit: "lb" },
				{ item: "stockfish", qty: 0.25, unit: "lb" },
				{ item: "cocoyam paste", qty: 0.5, unit: "cup" },
				{ item: "palm oil", qty: 0.25, unit: "cup" },
				{ item: "ground crayfish", qty: 2, unit: "tbsp" },
				{ item: "stock cubes", qty: 2, unit: "pcs" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
			],
			steps: [
				"Cook meat and stockfish until soft",
				"Add cocoyam paste to thicken",
				"Pour in palm oil, crayfish, and seasonings",
				"Add Oha leaves last and cook for 5 minutes",
				"Adjust salt to taste",
			],
		},
		{
			id: "tuwo-shinkafa",
			name: "Tuwo Shinkafa",
			image: "assets/images/tuwo-shinkafa.png",
			description:
				"Soft rice meal popular in Northern Nigeria, served with soup",
			time: 40,
			servings: 5,
			difficulty: "Easy",
			ingredients: [
				{ item: "soft rice", qty: 2, unit: "cups" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
			],
			steps: [
				"Boil rice with water until very soft",
				"Mash and stir continuously until thick",
				"Mold into balls and serve hot with soup",
			],
		},
		{
			id: "banga-soup",
			name: "Banga Soup",
			image: "assets/images/banga-soup.png",
			description:
				"Palm fruit soup with meat and spices, native to Delta region",
			time: 60,
			servings: 6,
			difficulty: "Medium",
			ingredients: [
				{ item: "palm fruit extract", qty: 4, unit: "cups" },
				{ item: "assorted meat", qty: 1, unit: "lb" },
				{ item: "dried fish", qty: 0.5, unit: "lb" },
				{ item: "Banga spice mix", qty: 2, unit: "tbsp" },
				{ item: "ground crayfish", qty: 2, unit: "tbsp" },
				{ item: "small onion", qty: 1, unit: "pc" },
				{ item: "stock cubes", qty: 2, unit: "pcs" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
			],
			steps: [
				"Cook meat until tender",
				"Add palm fruit extract and bring to boil",
				"Add fish, crayfish, spices, and onion",
				"Simmer for 20–30 mins until thick",
				"Season with salt and serve",
			],
		},
		{
			id: "ukodo",
			name: "Ukodo (Yam Pepper Soup)",
			image: "assets/images/ukodo.jpg",
			description: "Delta-style pepper soup made with yam and goat meat",
			time: 50,
			servings: 5,
			difficulty: "Medium",
			ingredients: [
				{ item: "goat meat", qty: 2, unit: "lbs" },
				{ item: "yam chunks", qty: 3, unit: "cups" },
				{ item: "pepper soup spice", qty: 1, unit: "tbsp" },
				{ item: "onion", qty: 1, unit: "pc" },
				{ item: "scotch bonnet peppers", qty: 2, unit: "pcs" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
				{ item: "scent leaves", qty: 1, unit: "handful" },
			],
			steps: [
				"Boil goat meat with spices until half done",
				"Add yam and cook until soft",
				"Add onions, peppers, and scent leaves",
				"Cook until yam thickens the soup",
				"Serve hot",
			],
		},
		{
			id: "fisherman-soup",
			name: "Fisherman Soup",
			image: "assets/images/fisherman-soup.png",
			description: "Rivers-style soup packed with seafood and spice",
			time: 60,
			servings: 6,
			difficulty: "Hard",
			ingredients: [
				{ item: "fresh fish", qty: 1, unit: "lbs" },
				{ item: "prawns", qty: 0.5, unit: "lbs" },
				{ item: "palm oil", qty: 0.25, unit: "cup" },
				{ item: "pepper soup spice", qty: 1, unit: "tbsp" },
				{ item: "ground crayfish", qty: 2, unit: "tbsp" },
				{ item: "stock cubes", qty: 2, unit: "pcs" },
				{ item: "onion", qty: 1, unit: "pc" },
				{ item: "scotch bonnet peppers", qty: 2, unit: "pcs" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
			],
			steps: [
				"Clean and season fish and prawns",
				"Boil with onions and spices",
				"Add crayfish, oil, and seasoning",
				"Simmer until fish is cooked through",
				"Serve with hot swallow",
			],
		},
		{
			id: "ofada-stew",
			name: "Ofada Stew (Ayamase)",
			image: "assets/images/ofada-stew.png",
			description: "Spicy green pepper stew typically served with Ofada rice",
			time: 60,
			servings: 5,
			difficulty: "Hard",
			ingredients: [
				{ item: "green bell peppers ", qty: 2, unit: "cups" },
				{ item: "unripe habanero peppers", qty: 0.5, unit: "cup" },
				{ item: "palm oil (bleached)", qty: 0.5, unit: "cup" },
				{ item: "assorted meats", qty: 1, unit: "lb" },
				{ item: "iru (locust beans)", qty: 2, unit: "tbsp" },
				{ item: "onion", qty: 1, unit: "pc" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
			],
			steps: [
				"Blend peppers and boil to reduce water",
				"Bleach palm oil and add onions",
				"Add meats and iru, fry briefly",
				"Add pepper mix and cook for 20 mins",
				"Season with salt and serve",
			],
		},
		{
			id: "catfish-pepper-soup",
			name: "Catfish Pepper Soup",
			image: "assets/images/Catfish Pepper Soup.jpg",
			description: "Spicy soup made with fresh catfish and herbs",
			time: 30,
			servings: 4,
			difficulty: "Easy",
			ingredients: [
				{ item: "catfish", qty: 2, unit: "lbs" },
				{ item: "pepper soup spice", qty: 1, unit: "tbsp" },
				{ item: "onion", qty: 1, unit: "pc" },
				{ item: "scent leaves", qty: 1, unit: "handful" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
			],
			steps: [
				"Place catfish in pot, add spices and onion",
				"Boil gently for 15 minutes",
				"Add scent leaves and cook 5 more mins",
				"Serve hot",
			],
		},
		{
			id: "gizdodo",
			name: "Gizdodo",
			image: "assets/images/Gizdodo.png",
			description: "Delicious combo of gizzard and plantain in spicy sauce",
			time: 45,
			servings: 5,
			difficulty: "Medium",
			ingredients: [
				{ item: "fried plantain", qty: 2, unit: "cups" },
				{ item: "chicken gizzards", qty: 1, unit: "lb" },
				{ item: "red bell peppers", qty: 2, unit: "pcs" },
				{ item: "onion", qty: 1, unit: "pc" },
				{ item: "scotch bonnet pepper", qty: 1, unit: "pc" },
				{ item: "Vegetable oil", qty: 0.25, unit: "cup" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
			],
			steps: [
				"Boil and fry gizzards",
				"Fry blended peppers and onions into a sauce",
				"Add fried gizzards and plantain to sauce",
				"Simmer together for 5–10 minutes",
			],
		},
		{
			id: "owo-soup",
			name: "Owo Soup",
			image: "assets/images/Owo.png",
			description: "Urhobo delicacy made with potash and palm oil",
			time: 35,
			servings: 4,
			difficulty: "Medium",
			ingredients: [
				{ item: "palm oil", qty: 0.25, unit: "cups" },
				{ item: "potash solution", qty: 1, unit: "tsp" },
				{ item: "blended tomatoes", qty: 0.5, unit: "cup" },
				{ item: "ground crayfish", qty: 1, unit: "tbsp" },
				{ item: "onion", qty: 1, unit: "pc" },
				{ item: "meat/fish", qty: 1, unit: "lb" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
			],
			steps: [
				"Cook meat or fish separately",
				"Mix oil and potash to form yellow paste",
				"Add tomato and crayfish mixture",
				"Add meat/fish and simmer gently",
				"Adjust seasoning and serve",
			],
		},
		{
			id: "ewa-agoyin",
			name: "Ewa Agoyin",
			image: "assets/images/Ewa Agoyin.png",
			description: "Soft mashed beans with spicy pepper sauce",
			time: "1 hour",
			servings: 5,
			difficulty: "Medium",
			ingredients: [
				{ item: "beans", qty: 2, unit: "cups" },
				{ item: "onion", qty: 1, unit: "pc" },
				{ item: "dried red peppers", qty: 3, unit: "pcs" },
				{ item: "palm oil", qty: 0.25, unit: "cup" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
			],
			steps: [
				"Cook beans until very soft, then mash",
				"Fry onions and pepper in palm oil",
				"Serve mashed beans with spicy sauce",
			],
		},
		{
			id: "nigerian-fried-rice",
			name: "Nigerian Fried Rice",
			image: "assets/images/Nigerian Fried Rice.png",
			description: "Colorful stir-fried rice with vegetables and liver",
			time: 40,
			servings: 6,
			difficulty: "Medium",
			ingredients: [
				{ item: "cooked rice", qty: 3, unit: "cups" },
				{ item: "chopped carrots", qty: 0.5, unit: "cup" },
				{ item: "green peas", qty: 0.5, unit: "cup" },
				{ item: "diced liver", qty: 0.5, unit: "cup" },
				{ item: "onion", qty: 1, unit: "pc" },
				{ item: "curry powder", qty: 1, unit: "tsp" },
				{ item: "Vegetable oil", qty: 0.25, unit: "cup" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
			],
			steps: [
				"Stir-fry vegetables and liver in oil",
				"Add rice and seasoning",
				"Mix well and fry for 10 minutes",
				"Serve hot",
			],
		},
		{
			id: "boiled-yam-and-egg-sauce",
			name: "Boiled Yam and Egg Sauce",
			image: "assets/images/Boiled Yam and Egg Sauce.png",
			description:
				"Simple and hearty dish of boiled yam served with tomato-egg sauce",
			time: 30,
			servings: 4,
			difficulty: "Easy",
			ingredients: [
				{ item: "yam", qty: 2, unit: "lbs" },
				{ item: "eggs", qty: 3, unit: "pcs" },
				{ item: "chopped tomatoes", qty: 2, unit: "pcs" },
				{ item: "sliced onion", qty: 1, unit: "pc" },
				{ item: "scotch bonnet pepper", qty: 1, unit: "pc" },
				{ item: "vegetable oil", qty: 2, unit: "tbsp" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
			],

			steps: [
				"Peel and boil yam until soft",
				"Heat oil, sauté onion, pepper, and tomatoes",
				"Crack eggs into pan and stir gently",
				"Season with salt and serve with yam",
			],
		},
		{
			id: "nigerian-meat-pie",
			name: "Nigerian Meat Pie",
			image: "assets/images/Nigerian Meat Pie.png",
			description: "Baked pastry filled with spiced minced meat and vegetables",
			time: 60,
			servings: 6,
			difficulty: "Hard",
			ingredients: [
				{ item: "flour", qty: 2, unit: "cups" },
				{ item: "butter", qty: 0.5, unit: "cup" },
				{ item: "minced beef", qty: 0.5, unit: "lb" },
				{ item: "diced onion", qty: 1, unit: "pc" },
				{ item: "diced potatoes", qty: 0.5, unit: "cup" },
				{ item: "egg (for sealing)", qty: 1, unit: "pc" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
			],
			steps: [
				"Prepare dough with flour, butter, and water",
				"Cook beef with onion, potatoes, and seasoning",
				"Roll out dough, fill with meat mix, and seal with egg wash",
				"Bake at 180°C for 30 minutes",
			],
		},
		{
			id: "isi-ewu",
			name: "Isi Ewu",
			image: "assets/images/Isi Ewu.png",
			description: "Spicy goat head delicacy served with palm oil sauce",
			time: 90,
			servings: 4,
			difficulty: "Hard",
			ingredients: [
				{ item: "goat head", qty: 1, unit: "as needed" },
				{ item: "palm oil", qty: 0.25, unit: "cup" },
				{ item: "potash solution", qty: 1, unit: "tbsp" },
				{ item: "ground crayfish", qty: 2, unit: "tbsp" },
				{ item: "scotch bonnet peppers", qty: 2, unit: "pcs" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
				{
					item: "Utazi leaves and onion rings for garnish",
					qty: 1,
					unit: "as needed",
				},
			],
			steps: [
				"Boil goat head until tender",
				"Mix oil and potash, add seasonings and peppers",
				"Toss goat head in sauce and simmer for 10 mins",
				"Garnish with onions and utazi leaves",
			],
		},
		{
			id: "beans-porridge",
			name: "Beans Porridge (Ewa Oloyin)",
			image: "assets/images/Beans Porridge (Ewa Oloyin).png",
			description: "Honey beans cooked with palm oil and spices",
			time: 90,
			servings: 5,
			difficulty: "Easy",
			ingredients: [
				{ item: "honey beans", qty: 2, unit: "cups" },
				{ item: "palm oil", qty: 0.25, unit: "cup" },
				{ item: "small onion", qty: 1, unit: "pc" },
				{ item: "scotch bonnet pepper", qty: 1, unit: "pc" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
			],
			steps: [
				"Cook beans until very soft",
				"Add oil, onions, pepper and salt",
				"Mash lightly and simmer until thick",
			],
		},
		{
			id: "yam-porridge",
			name: "Yam Porridge (Asaro)",
			image: "assets/images/Yam Porridge (Asaro).png",
			description: "Savory yam porridge in palm oil and tomato sauce",
			time: 45,
			servings: 4,
			difficulty: "Medium",
			ingredients: [
				{ item: "yam", qty: 2, unit: "lbs" },
				{ item: "palm oil", qty: 0.25, unit: "cup" },
				{ item: "tomatoes", qty: 2, unit: "pcs" },
				{ item: "onion", qty: 1, unit: "pc" },
				{ item: "scotch bonnet pepper", qty: 1, unit: "pc" },
				{ item: "ground crayfish", qty: 2, unit: "tbsp" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
			],
			steps: [
				"Boil yam with chopped tomato, onion and pepper",
				"Add palm oil and crayfish, mash partially",
				"Simmer until thick and tasty",
			],
		},
		{
			id: "nigerian-chin-chin",
			name: "Nigerian Chin Chin",
			image: "assets/images/Nigerian Chin Chin.png",
			description: "Crunchy fried snack made with sweet dough",
			time: 60,
			servings: 6,
			difficulty: "Medium",
			ingredients: [
				{ item: "flour", qty: 3, unit: "cups" },
				{ item: "sugar", qty: 0.5, unit: "cup" },
				{ item: "milk", qty: 0.5, unit: "cup" },
				{ item: "butter", qty: 0.5, unit: "cup" },
				{ item: "egg", qty: 1, unit: "pc" },
				{ item: "nutmeg", qty: 1, unit: "tsp" },
				{ item: "oil for frying", qty: 1, unit: "enough" },
			],
			steps: [
				"Mix all ingredients to form dough",
				"Roll out and cut into small pieces",
				"Fry in hot oil until golden brown",
			],
		},
		{
			id: "stewed-snail",
			name: "Stewed Snail",
			image: "assets/images/Stewed Snail.jpg",
			description: "Deliciously spicy Nigerian snail dish",
			time: 45,
			servings: 4,
			difficulty: "Hard",
			ingredients: [
				{ item: "cleaned snails", qty: 1, unit: "lb" },
				{ item: "blended tomatoes", qty: 3, unit: "cups" },
				{ item: "onion", qty: 1, unit: "pc" },
				{ item: "scotch bonnet peppers", qty: 2, unit: "pcs" },
				{ item: "vegetable oil", qty: 0.25, unit: "cup" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
			],
			steps: [
				"Boil snails with salt and onions",
				"Fry tomato sauce until thick",
				"Add snails and simmer for 10 minutes",
			],
		},
		{
			id: "stewed-turkey",
			name: "Stewed Turkey",
			image: "assets/images/Stewed Turkey.png",
			description: "Turkey simmered in spicy tomato sauce",
			time: 60,
			servings: 6,
			difficulty: "Medium",
			ingredients: [
				{ item: "turkey", qty: 2, unit: "lbs" },
				{ item: "blended tomatoes", qty: 4, unit: "cups" },
				{ item: "onion", qty: 1, unit: "pc" },
				{ item: "scotch bonnet peppers", qty: 2, unit: "pcs" },
				{ item: "vegetable oil", qty: 0.25, unit: "cup" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
			],
			steps: [
				"Boil turkey until tender, fry or grill if desired",
				"Fry blended tomato sauce with onions and pepper",
				"Add turkey to sauce and simmer",
			],
		},
		{
			id: "egusi-ijebu",
			name: "Egusi Ijebu",
			image: "assets/images/Egusi Ijebu.png",
			description: "Variation of egusi soup with smooth texture, no lumps",
			time: 45,
			servings: 5,
			difficulty: "Medium",
			ingredients: [
				{ item: "ground egusi", qty: 1.5, unit: "cups" },
				{ item: "palm oil", qty: 0.25, unit: "cup" },
				{ item: "meat or fish", qty: 1, unit: "lb" },
				{ item: "onion", qty: 1, unit: "pc" },
				{ item: "scotch bonnet peppers", qty: 2, unit: "pcs" },
				{ item: "ground crayfish", qty: 2, unit: "tbsp" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
			],
			steps: [
				"Cook meat or fish separately",
				"Blend egusi with water into smooth paste",
				"Fry paste in palm oil, add stock, simmer until thick",
				"Add protein and seasonings, cook for 10 mins",
			],
		},
		{
			id: "plantain-frittata",
			name: "Plantain Frittata",
			image: "assets/images/Plantain Frittata.png",
			description: "Baked eggs and plantain dish perfect for breakfast",
			time: 30,
			servings: 4,
			difficulty: "Easy",
			ingredients: [
				{ item: "ripe plaintains", qty: 2, unit: "pcs" },
				{ item: "eggs", qty: 4, unit: "pcs" },
				{ item: "bell pepper", qty: 1, unit: "pc" },
				{ item: "onion", qty: 1, unit: "pc" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
				{ item: "Oil for frying", qty: 1, unit: "as needed" },
			],
			steps: [
				"Fry plantains and set aside",
				"Beat eggs and mix with chopped veggies and seasoning",
				"Pour mixture into baking pan with plantains",
				"Bake at 180°C for 15–20 minutes",
			],
		},
		{
			id: "okpa",
			name: "Okpa",
			image: "assets/images/okpa.png",
			description: "Savory steamed Bambara nut flour pudding from the East",
			time: 60,
			servings: 6,
			difficulty: "Medium",
			ingredients: [
				{ item: "okpa", qty: 2, unit: "cups" },
				{ item: "palm oil", qty: 0.25, unit: "cup" },
				{ item: "ground pepper", qty: 2, unit: "tsp" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
				{ item: "Banana leaves or containers", qty: 1, unit: "as needed" },
			],
			steps: [
				"Mix flour with salt, pepper, and oil",
				"Add water to make smooth batter",
				"Pour into leaves or bowls and steam until firm",
			],
		},
		{
			id: "ogi-and-akara",
			name: "Ogi and Akara",
			image: "assets/images/Ogi and Akara.png",
			description: "Fermented corn pudding served with fried bean cakes",
			time: 60,
			servings: 4,
			difficulty: "Medium",

			ingredients: [
				{ item: "fermented corn paste (ogi)", qty: 2, unit: "cups" },
				{ item: "black-eyed beans", qty: 2, unit: "cups" },
				{ item: "small onion", qty: 1, unit: "pc" },
				{ item: "scotch bonnet", qty: 1, unit: "pc" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
				{ item: "Oil for frying", qty: 1, unit: "enough" },
			],
			steps: [
				"Cook ogi with water, stirring constantly until thick",
				"Blend beans with onion and pepper, season and fry spoonfuls in hot oil until golden",
				"Serve hot akara with warm ogi",
			],
		},
		{
			id: "boli",
			name: "Boli (Roasted Plantain)",
			image: "assets/images/Boli.png",
			description: "Char-grilled ripe plantains served with spicy pepper sauce",
			time: 30,
			servings: 3,
			difficulty: "Easy",
			ingredients: [
				{ item: "ripe plantains", qty: 3, unit: "pcs" },
				{ item: "oil (optional)", qty: 1, unit: "tbsp" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
			],
			steps: [
				"Peel plantains and roast over open flame or in oven until golden brown",
				"Optionally brush with oil and sprinkle salt",
				"Serve with spicy pepper sauce or groundnut",
			],
		},
		{
			id: "coconut-rice",
			name: "Coconut Rice",
			image: "assets/images/Coconut Rice.png",
			description: "Flavored rice cooked with coconut milk and spices",
			time: 50,
			servings: 6,
			difficulty: "Medium",
			ingredients: [
				{ item: "rice", qty: 3, unit: "cups" },
				{ item: "coconut milk", qty: 2, unit: "cups" },
				{ item: "meat or fish stock", qty: 0.5, unit: "cup" },
				{ item: "onion", qty: 1, unit: "pc" },
				{ item: "oil", qty: 0.25, unit: "cup" },
				{ item: "bell pepper", qty: 1, unit: "pc" },
				{ item: "curry powder", qty: 1, unit: "tsp" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
			],
			steps: [
				"Sauté onions and peppers in oil",
				"Add rice, coconut milk, and stock",
				"Season and cook until rice is tender",
			],
		},
		{
			id: "ogbono-soup",
			name: "Ogbono Soup",
			image: "assets/images/Ogbono Soup.png",
			description: "Thick Nigerian draw soup made from wild mango seeds",
			time: 60,
			servings: 5,
			difficulty: "Medium",
			ingredients: [
				{ item: "ogbono seeds", qty: 1, unit: "cup" },
				{ item: "palm oil", qty: 0.5, unit: "cup" },
				{ item: "assorted meat", qty: 1, unit: "lb" },
				{ item: "stockfish", qty: 0.5, unit: "lb" },
				{ item: "ground crayfish", qty: 2, unit: "tbsp" },
				{ item: "spinach or bitterleaf", qty: 2, unit: "cups" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
			],
			steps: [
				"Cook meat and stockfish till soft",
				"Heat palm oil, add ogbono and stir continuously",
				"Add meat stock, then crayfish and seasonings",
				"Add vegetables and simmer until thick",
			],
		},
		{
			id: "ogiri-sauce-with-yam",
			name: "Ogiri Sauce with Yam",
			image: "assets/images/Ogiri Sauce with Yam.jpg",
			description:
				"A rich, fermented African locust bean sauce served with boiled yam",
			time: 35,
			servings: 4,
			difficulty: "Medium",
			ingredients: [
				{ item: "ogiri (locust bean paste)", qty: 2, unit: "tbsp" },
				{ item: "onion", qty: 1, unit: "pc" },
				{ item: "scotch bonnet peppers", qty: 2, unit: "pcs" },
				{ item: "palm oil", qty: 0.25, unit: "cup" },
				{ item: "yam", qty: 2, unit: "lbs" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
			],
			steps: [
				"Boil yam in salted water until soft",
				"Fry onions and pepper in palm oil",
				"Add ogiri and stir well",
				"Serve hot with yam",
			],
		},
		{
			id: "ofada-rice-and-ayamase-sauce",
			name: "Ofada Rice and Ayamase Sauce",
			image: "assets/images/Ofada Rice and Ayamase Sauce.jpg",
			description: "Local Nigerian rice served with spicy green pepper stew",
			time: 60,
			servings: 5,
			difficulty: "Hard",
			ingredients: [
				{ item: "ofada rice", qty: 2, unit: "cups" },
				{ item: "bleached palm oil", qty: 0.5, unit: "cup" },
				{ item: "green bell peppers", qty: 1, unit: "cup" },
				{ item: "assorted meat", qty: 0.5, unit: "lb" },
				{ item: "locust beans", qty: 1, unit: "tbsp" },
				{ item: "onion", qty: 1, unit: "pc" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
			],
			steps: [
				"Cook rice until soft, set aside",
				"Blend peppers and boil out excess water",
				"Bleach palm oil, add onion and locust beans",
				"Add pepper mix and meats, simmer till thick",
				"Serve with Ofada rice",
			],
		},
		{
			id: "achicha",
			name: "Achicha",
			image: "assets/images/achicha.webp",
			description:
				"Igbo delicacy made with dried cocoyam flakes and vegetables",
			time: 45,
			servings: 5,
			difficulty: "Hard",
			ingredients: [
				{ item: "achicha (dry cocoyam)", qty: 2, unit: "cups" },
				{ item: "ugba (oil bean)", qty: 1, unit: "cup" },
				{ item: "palm oil", qty: 0.25, unit: "cup" },
				{ item: "onion", qty: 1, unit: "pc" },
				{ item: "crayfish", qty: 2, unit: "tbsp" },
				{ item: "Salt and pepper", qty: 1, unit: "to taste" },
				{ item: "pumpkin leaves", qty: 2, unit: "cups" },
			],
			steps: [
				"Soak achicha and steam until soft",
				"Sauté onions, crayfish, and pepper in palm oil",
				"Add ugba and leaves, mix with achicha and cook",
			],
		},
		{
			id: "fish-stew",
			name: "Fish Stew",
			image: "assets/images/Fish Stew.png",
			description: "Tomato-based stew with fried or grilled fish",
			time: 45,
			servings: 4,
			difficulty: "Medium",
			ingredients: [
				{ item: "whole fish", qty: 2, unit: "pcs" },
				{ item: "blended tomatoes", qty: 5, unit: "pcs" },
				{ item: "scotch bonnet peppers", qty: 2, unit: "pcs" },
				{ item: "onion", qty: 1, unit: "pc" },
				{ item: "vegetable oil", qty: 0.25, unit: "cup" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
			],
			steps: [
				"Fry or grill fish and set aside",
				"Blend and cook tomato mix until thick",
				"Add oil, seasoning, and fish",
				"Simmer gently to absorb flavors",
			],
		},
		{
			id: "nigerian-pancake",
			name: "Nigerian Pancake",
			image: "assets/images/Nigerian Pancake.png",
			description: "Savory spiced pancake, popular for breakfast",
			time: 25,
			servings: 4,
			difficulty: "Easy",
			ingredients: [
				{ item: "flour", qty: 1, unit: "cup" },
				{ item: "eggs", qty: 2, unit: "pcs" },
				{ item: "milk", qty: 1, unit: "cup" },
				{ item: "sugar", qty: 1, unit: "tbsp" },
				{ item: "pepper", qty: 1, unit: "tsp" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
				{ item: "onion (grated)", qty: 1, unit: "pc" },
				{ item: "oil for frying", qty: 1, unit: "as needed" },
			],
			steps: [
				"Mix all ingredients into a smooth batter",
				"Pour a scoop into a hot pan with oil",
				"Fry until golden on both sides",
			],
		},
		{
			id: "abacha-african-salad",
			name: "Abacha (African Salad)",
			image: "assets/images/Abacha (African Salad).webp",
			description:
				"A savory mix of cassava flakes, palm oil, and local ingredients",
			time: 45,
			servings: 5,
			difficulty: "Medium",
			ingredients: [
				{ item: "abacha (cassava flakes)", qty: 2, unit: "cups" },
				{ item: "palm oil", qty: 0.25, unit: "cup" },
				{ item: "potash water", qty: 1, unit: "tbsp" },
				{ item: "onion", qty: 1, unit: "pc" },
				{ item: "ugba (oil bean)", qty: 1, unit: "cup" },
				{ item: "crayfish, pepper, and seasoning", qty: 1, unit: "as needed" },
				{ item: "garden eggs and utazi leaves", qty: 1, unit: "as needed" },
			],
			steps: [
				"Soak abacha in hot water and drain",
				"Mix oil with potash until thickened",
				"Add ingredients and stir in abacha",
				"Garnish and serve",
			],
		},
		{
			id: "garden-egg-sauce",
			name: "Garden Egg Sauce",
			image: "assets/images/Garden Egg Sauce.png",
			description: "Eggplant-based sauce perfect with boiled yam or rice",
			time: 35,
			servings: 4,
			difficulty: "Easy",
			ingredients: [
				{ item: "garden eggs", qty: 6, unit: "pcs" },
				{ item: "onion", qty: 0.5, unit: "pc" },
				{ item: "palm oil", qty: 2, unit: "tbsp" },
				{ item: "scotch bonnet peppers", qty: 2, unit: "pcs" },
				{ item: "stock cube", qty: 1, unit: "pc" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
			],
			steps: [
				"Boil and mash garden eggs",
				"Sauté onions and pepper in palm oil",
				"Add mashed eggplants and seasoning",
				"Cook till well combined and thick",
			],
		},
		{
			id: "peppered-gizzard",
			name: "Peppered Gizzard",
			image: "assets/images/Peppered Gizzard.png",
			description: "Spicy stir-fried gizzards in rich pepper sauce",
			time: 45,
			servings: 5,
			difficulty: "Medium",
			ingredients: [
				{ item: "chicken gizzards", qty: 1, unit: "lb" },
				{ item: "blended pepper mix", qty: 1, unit: "cup" },
				{ item: "onion", qty: 1, unit: "pc" },
				{ item: "vegetable oil", qty: 2, unit: "tbsp" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
			],
			steps: [
				"Boil and fry gizzards till brown",
				"Stir-fry pepper mix with onions and oil",
				"Add gizzards, season and simmer till coated",
			],
		},
		{
			id: "puff-puff",
			name: "Puff Puff",
			image: "assets/images/Puff Puff.png",
			description: "Sweet, deep-fried Nigerian dough balls",
			time: 60,
			servings: 6,
			difficulty: "Easy",
			ingredients: [
				{ item: "flour", qty: 2, unit: "cups" },
				{ item: "sugar", qty: 0.5, unit: "cup" },
				{ item: "yeast", qty: 2, unit: "tsp" },
				{ item: "warm water", qty: 1.5, unit: "cups" },
				{ item: "salt", qty: 0.5, unit: "tsp" },
				{ item: "oil for frying", qty: 1, unit: "enough" },
			],
			steps: [
				"Mix dry ingredients and add water to form thick batter",
				"Let rise for 45 mins",
				"Fry in hot oil until golden brown",
			],
		},

		{
			id: "spaghetti-jollof",
			name: "Spaghetti Jollof",
			image: "assets/images/Spaghetti Jollof.jpg",
			description: "Delicious jollof-style spaghetti cooked in tomato sauce",
			time: 35,
			servings: 5,
			difficulty: "Easy",
			ingredients: [
				{ item: "spaghetti", qty: 1, unit: "pack" },
				{ item: "blended tomatoes and pepper", qty: 4, unit: "cups" },
				{ item: "onion", qty: 1, unit: "pc" },
				{ item: "vegetable oil", qty: 0.25, unit: "cup" },
				{ item: "seasoning cubes", qty: 2, unit: "pcs" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
			],
			steps: [
				"Boil spaghetti and drain",
				"Cook pepper mix with onion and seasoning",
				"Add spaghetti and stir well",
				"Simmer till sauce is absorbed",
			],
		},
		{
			id: "dan-wake",
			name: "Dan Wake",
			image: "assets/images/dan wake.jpg",
			description:
				"Steamed dumplings made from bean or maize flour, often served with soup",
			time: 45,
			servings: 6,
			difficulty: "Medium",
			ingredients: [
				{ item: "bean flour or maize flour", qty: 2, unit: "cups" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
				{ item: "Water for mixing", qty: 1, unit: "as needed" },
			],
			steps: [
				"Mix flour with salt and water to form a thick batter",
				"Pour batter into boiling water in small portions",
				"Cook until dumplings float and are firm",
				"Serve with traditional Hausa soups",
			],
		},

		{
			id: "akara-with-custard",
			name: "Akara with Custard",
			image: "assets/images/Akara with Custard.png",
			description:
				"Akara paired with hot creamy custard, a Nigerian breakfast favorite",
			time: 35,
			servings: 4,
			difficulty: "Easy",
			ingredients: [
				{ item: "akara (bean cake)", qty: 1, unit: "cup" },
				{ item: "custard powder", qty: 0.5, unit: "cup" },
				{ item: "sugar", qty: 2, unit: "tbsp" },
				{ item: "Hot water", qty: 1, unit: "as needed" },
				{ item: "Milk (optional)", qty: 1, unit: "as needed" },
			],
			steps: [
				"Prepare custard with hot water and stir until smooth",
				"Blend beans with onion and pepper, season and fry spoonfuls in hot oil until golden",
				"Serve with freshly fried akara on the side",
			],
		},
		{
			id: "rice-and-beans",
			name: "Rice and Beans",
			image: "assets/images/Rice and Beans.png",
			description:
				"A classic Nigerian combo of boiled rice and beans, served with stew or sauce",
			time: 50,
			servings: 4,
			difficulty: "Easy",
			ingredients: [
				{ item: "parboiled rice", qty: 1, unit: "cup" },
				{ item: "black-eyed beans or honey beans", qty: 1, unit: "cup" },
				{ item: "water", qty: 6, unit: "cups" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
			],
			steps: [
				"Rinse beans and boil until tender, then drain",
				"Rinse rice thoroughly",
				"Add rice and beans to a pot with water and salt",
				"Cook until rice is soft and water is absorbed",
				"Serve with stew, fried plantains, or sauce",
			],
		},
		{
			id: "white-rice",
			name: "White Rice",
			image: "assets/images/White Rice.png",
			description: "Simple boiled white rice, often served with stew or sauce",
			time: 30,
			servings: 4,
			difficulty: "Easy",
			ingredients: [
				{ item: "long grain parboiled rice", qty: 2, unit: "cups" },
				{ item: "water", qty: 6, unit: "cups" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
			],
			steps: [
				"Rinse rice thoroughly until water runs clear",
				"Boil water in a pot and add salt",
				"Add rice and cook on medium heat until tender",
				"Drain excess water if necessary and fluff with fork",
				"Serve with stew, beans, or sauce of choice",
			],
		},
		{
			id: "indomie-noodles",
			name: "Indomie Noodles",
			image: "assets/images/Indomie Noodles.png",
			description:
				"Instant noodles cooked with vegetables, eggs, and spices the Nigerian way",
			time: 15,
			servings: 2,
			difficulty: "Easy",
			ingredients: [
				{ item: "Indomie noodles (or instant noodles)", qty: 2, unit: "packs" },
				{ item: "mixed vegetables", qty: 0.5, unit: "cup" },
				{ item: "onion", qty: 1, unit: "small" },
				{ item: "scotch bonnet (optional)", qty: 1, unit: "pc" },
				{ item: "egg (optional)", qty: 1, unit: "pc" },
				{ item: "oil (optional)", qty: 1, unit: "tbsp" },
				{ item: "Seasoning from noodle packs", qty: 1, unit: "as needed" },
			],
			steps: [
				"Heat oil in a pan and sauté onions and pepper",
				"Add mixed vegetables and stir for 2 minutes",
				"Add water and bring to a boil",
				"Add noodles and seasoning, cook for 2 minutes",
				"Crack in the egg, stir and cook until noodles are soft",
				"Serve hot",
			],
		},
		{
			id: "shawarma",
			name: "Shawarma",
			image: "assets/images/Shawarma.png",
			description:
				"Popular street food wrap made with grilled spiced chicken, veggies, and cream in flatbread",
			time: "45 mins",
			servings: 2,
			difficulty: "Medium",
			ingredients: [
				{ item: "pita breads or tortilla wraps", qty: 2, unit: "pcs" },
				{ item: "chicken breasts", qty: 2, unit: "pcs" },
				{ item: "paprika", qty: 0.5, unit: "tsp" },
				{ item: "curry powder", qty: 0.5, unit: "tsp" },
				{ item: "thyme", qty: 0.25, unit: "tsp" },
				{ item: "garlic powder", qty: 0.25, unit: "tsp" },
				{ item: "vegetable oil", qty: 1, unit: "tbsp" },
				{ item: "chili powder (optional)", qty: 0.5, unit: "tsp" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
				{ item: "onion", qty: 0.5, unit: "pc" },
				{ item: "bell pepper", qty: 0.5, unit: "pc" },
				{
					item: "Mayonnaise + ketchup (for cream sauce)",
					qty: 1,
					unit: "as needed",
				},
				{
					item: "Optional: cabbage, carrots, sausage",
					qty: 1,
					unit: "as needed",
				},
			],
			steps: [
				"Season chicken with spices and let marinate (optional)",
				"Heat oil in pan and stir-fry chicken until fully cooked",
				"Warm pita bread slightly, spread with cream sauce",
				"Add chicken, onions, peppers, and other fillings",
				"Wrap tightly and grill or toast for 1–2 minutes",
				"Serve warm",
			],
		},
		{
			id: "ewedu-and-swallow",
			name: "Ewedu and Swallow",
			image: "assets/images/Ewedu and Swallow.png",
			description:
				"Yoruba jute leaf soup typically served with amala, eba, or fufu",
			time: 25,
			servings: 3,
			difficulty: "Easy",
			ingredients: [
				{ item: "fresh ewedu leaves (jute leaves)", qty: 2, unit: "cups" },
				{ item: "ground crayfish", qty: 1, unit: "tsp" },
				{ item: "locust beans (iru)", qty: 1, unit: "tsp" },
				{ item: "potash (kaun)", qty: 0.5, unit: "tsp" },
				{ item: "water", qty: 1, unit: "cup" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
				{
					item: "Swallow of choice (amala, eba, or fufu)",
					qty: 1,
					unit: "as needed",
				},
			],
			steps: [
				"Wash and boil ewedu leaves with potash for 5–7 minutes",
				"Blend or whisk until smooth and drawy",
				"Return to heat, add crayfish, iru, and salt",
				"Simmer for 2–3 minutes and serve hot",
				"Serve with your preferred swallow and stew",
			],
		},
		{
			id: "gbegiri-soup",
			name: "Gbegiri Soup",
			image: "assets/images/Gbegiri Soup.png",
			description:
				"Traditional Yoruba soup made from peeled beans, often paired with ewedu and amala",
			time: 60,
			servings: 4,
			difficulty: "Medium",
			ingredients: [
				{ item: "peeled brown beans", qty: 2, unit: "cups" },
				{ item: "palm oil", qty: 1, unit: "tbsp" },
				{ item: "ground crayfish", qty: 1, unit: "tbsp" },
				{ item: "ground pepper", qty: 1, unit: "tsp" },
				{ item: "stock cube", qty: 1, unit: "pc" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
				{ item: "onion", qty: 0.5, unit: "pc" },
			],
			steps: [
				"Boil peeled beans with onion until very soft",
				"Mash or blend into a smooth puree",
				"Return to heat and add palm oil, crayfish, and pepper",
				"Season with stock cube and salt",
				"Simmer for 5–10 minutes until thick",
				"Serve with ewedu and amala",
			],
		},
		{
			id: "fried-yam-and-egg-sauce",
			name: "Fried Yam and Egg Sauce",
			image: "assets/images/Fried Yam and Egg Sauce.png",
			description:
				"Golden crispy yam slices served with spicy scrambled egg sauce",
			time: 35,
			servings: 3,
			difficulty: "Easy",
			ingredients: [
				{ item: "yam (peeled and sliced)", qty: 2, unit: "lbs" },
				{ item: "vegetable oil for frying", qty: 1, unit: "as needed" },
				{ item: "eggs", qty: 4, unit: "pcs" },
				{ item: "tomato", qty: 1, unit: "pc" },
				{ item: "onion", qty: 1, unit: "pc" },
				{ item: "scotch bonnet", qty: 1, unit: "pc" },
				{ item: "oil (optional)", qty: 1, unit: "tbsp" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
			],
			steps: [
				"Peel, slice, and boil yam slightly with salt for 5–7 minutes",
				"Drain and deep-fry until golden brown",
				"Heat 1 tbsp oil in a pan and sauté onions, tomato, and pepper",
				"Crack in eggs, season, and scramble until fully cooked",
				"Serve fried yam with egg sauce hot",
			],
		},
		{
			id: "nigerian-toasted-bread-sandwich",
			name: "Nigerian Toasted Bread Sandwich",
			image: "assets/images/Nigerian Toasted Bread Sandwich.png",
			description:
				"Crunchy toasted bread sandwich filled with eggs, carrots, cabbage, and fresh veggies",
			time: 15,
			servings: 2,
			difficulty: "Easy",
			ingredients: [
				{ item: "bread", qty: 4, unit: "slices" },
				{ item: "margarine or butter", qty: 2, unit: "tbsp" },
				{ item: "boiled eggs", qty: 2, unit: "pcs" },
				{ item: "carrot", qty: 1, unit: "small" },
				{ item: "onion", qty: 1, unit: "small" },
				{ item: "cabbage", qty: 0.5, unit: "cup" },
				{ item: "tomato", qty: 1, unit: "pc" },
				{ item: "lettuce leaves", qty: 2, unit: "pcs" },
				{ item: "Salt to taste", qty: 1, unit: "to taste" },
				{
					item: "Mayonnaise or Nigerian pepper sauce (optional)",
					qty: 1,
					unit: "as needed",
				},
			],
			steps: [
				"Butter one side of each bread slice",
				"On the unbuttered side, layer sliced boiled eggs, grated carrot, shredded cabbage, onion, tomato, and lettuce",
				"Season with salt and pepper as preferred",
				"Add a little mayonnaise or pepper sauce if desired",
				"Top with another slice of bread, buttered side out",
				"Toast on a skillet over medium heat until golden brown and crispy",
				"Cut into halves and serve hot",
			],
		},
	]

	window.App.Data = {
		ensureSeeded: function () {
			// Always sync latest seeds to storage since recipes are not editable by user
			window.App.Storage.save("recipes", seeds)
			return seeds
		},
		all: function () {
			return window.App.Storage.load("recipes", []) || []
		},
		byId: function (id) {
			return (
				(window.App.Storage.load("recipes", []) || []).find(
					(r) => r.id === id
				) || null
			)
		},
	}
})()
